######################################################################
# Automatically generated by qmake (1.07a) Wed Oct 26 20:39:59 2011
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += fom.h
SOURCES += fom.cpp
