######################################################################
# Automatically generated by qmake (1.07a) Wed Oct 26 19:54:31 2011
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += awari.ui.h
INTERFACES += awari.ui
SOURCES += main.cpp
